# https://stackoverflow.com/questions/65499626/trigger-github-actions-if-push-in-another-repo/68407424#68407424
name: daily

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '* * * * *'

defaults:
  run:
    shell: bash
    working-directory: .github/workflows

jobs:
  is-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - run: bash ./is_latest.sh
